version: '3.8'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "1m" 

services:
  proxy:
    <<: *default-opts
    image: traefik:2.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-logs:/logs
      - ./certs:/certs
      - ./dynconf:/dynconf
    environment:
      TZ: "Europe/Warsaw"
    command:
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
        # Local development do not use SWARM
      - "--providers.docker.swarmMode=false"
      - "--providers.docker.network=traefik-public"

      - "--providers.file.directory=/dynconf"
      - "--providers.file.watch=true"


      - "--log=true"
      - "--log.filePath=/logs/traefik.log"
      - "--log.level=ERROR"
      - "--accesslog=false"
      - "--accesslog.filepath=/logs/access.log"
      - "--accesslog.bufferingsize=25"
      - "--api=true"
      - "--api.dashboard=true"

      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"


      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
        

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=80"
    networks:
      - traefik-public


networks:
  traefik-public:
    external: true
volumes:
  traefik-logs:
